services:
  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:4.2.1-management-alpine
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"    # AMQP protocol port
      - "15672:15672"  # HTTP management UI
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: user
    volumes:
      - rabbitmq_:/var/lib/rabbitmq

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"  # Porta para acessar o Zipkin
    environment:
      - ZIPKIN_HTTP_PORT=9411  # Garantir que o Zipkin ir√° rodar na porta 9411
    restart: always

volumes:
  postgres_:
  rabbitmq_:
